dol_ldap:
    domains:
        # First domain
        server1:
            driver:
                host: localhost
                port: 389
            user:
                baseDn: ou=users, dc=ldap, dc=com
                attributes:
                    - { ldap_attr: uid,  user_method: setUsername }
                    - { ldap_attr: mail,  user_method: setEmail }
                filter: (&(ObjectClass=person))
#            driver:
#                host: localhost
#                port: 389
##                username: cn=manager,ou=roles,dc=ldap,dc=com
#            user:
#                baseDn: ou=roles,dc=ldap,dc=com
#                filter: (&(ObjectClass=groupOfNames))
#                attributes:
#                    - { ldap_attr: samaccountname,  user_method: setUsername }
##                    - { ldap_attr: memberof,  user_method: addRole }

#    service:
#        user_hydrator: px.ldap.manager_hydrator