dol_ldap:
    domains:
        # First domain
        server1:
            driver:
                host: localhost
                port: 389
            user:
                baseDn: ou=users, dc=ldap, dc=com
                attributes:
                    - { ldap_attr: uid,  user_method: setUsername }
                    - { ldap_attr: mail,  user_method: setEmail }
                filter: (&(ObjectClass=person))